name: Crystal CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
  
      - name: Crystal Ameba Linter
        uses: crystal-ameba/github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Install dependencies
        run: shards install
  
      - name: Run tests
        run: crystal spec
